### ISSUE TITLE
Retrieving the reference db using google_drive_download.py

### ISSUE THREAD

**Issue by walidabualafia** [Xinglab/IRIS#8]
Hi,

I was attempting to install IRIS on our HPC cluster, and I am running into trouble with the data download script `google_drive_download.py`. 

I set up a Google service-account, and I passed the key as the instructions note. Here is the command I am running:
```python google_drive_download.py --iris-folder-id 1zhmXoajD5RyjxVTYbGZ-ebic1VPfEYKz --dest-dir IRIS_data --download-all --api-key-json-path iris-module-install-1a0df2bdaffd.json```

I am running this command from inside the parent directory, `./IRIS/` and I want to use the `--download-all` flag. I keep getting back the following error:
```Traceback (most recent call last):
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 187, in <module>
    main()
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 63, in main
    download_all_files(args.iris_folder_id, args.dest_dir,
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 132, in download_all_files
    write_file_tsv(all_files, TOP_DIR_NAME, temp_handle)
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 121, in write_file_tsv
    write_file_tsv(folder_dict['files'], full_path, tsv_handle)
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 121, in write_file_tsv
    write_file_tsv(folder_dict['files'], full_path, tsv_handle)
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 121, in write_file_tsv
    write_file_tsv(folder_dict['files'], full_path, tsv_handle)
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 117, in write_file_tsv
    write_tsv_line([full_path, file_dict['id']], tsv_handle)
  File "/shortened_path/iris/vendor/IRIS/google_drive_download.py", line 101, in write_tsv_line
    tsv_handle.write('{}\n'.format('\t'.join(columns)))
  File "/shortened_path/python/install/3.9.9/lib/python3.9/tempfile.py", line 478, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

Any pointers on where to go from here? I know that the script needs editing to take string instead of bytes, but I have not looked through the entire file yet.

Cheers,
Walid

**Comment by walidabualafia** [comment]
I just fixed the issue. Unfortunately, I could not commit it.

In `google_drive_download.py`, I changed the body of `write_tsv_line(columns, tsv_handle)` from:
```
tsv_handle.write('{}\n'.format('\t'.join(columns)))
```
To:
```
tsv_handle.write('{}\n'.format('\t'.join(columns)).encode())
```
This casts the string to bytes, and matches the types so that each written tsv_line is a byte stream rather than a string.

Cheers.

**Comment by EricKutschera** [comment]
Thanks for reporting this error. The temporary file was being opened without specifying if it should be a text or binary file and it defaulted to a binary file. I updated the code to open it as a text file since text tsv lines are going to be written

I think when I wrote that part of the script I was testing with Python2 which was ok with writing the string to a binary file
